version: '3.8'

services:
  db:
    image: mysql:8.0
    ports:
      - '6603:3306'
    environment:
      MYSQL_ROOT_PASSWORD: helloworld
    volumes:
      - db_data:/var/lib/mysql

  php:
    build: .
    volumes:
      - ./code:/code
    depends_on:
      - db
    links:
      - db
    ports:
      - "8080:80"

volumes:
  db_data:
